/**
 * scripts/capture/stills.mjs
 *
 * Captures the 7 "money screen" stills. Read-only: navigates, scrolls,
 * hovers — never clicks anything that creates/edits/sends/deletes. Reuses
 * the session saved by auth.mjs (run that first, or via preflight.mjs).
 *
 * Usage: node scripts/capture/stills.mjs
 */
import { chromium } from 'playwright';
import fs from 'node:fs';
import path from 'node:path';
import {
  BASE_URL, STATE_FILE, RAW_DIR, PROCESSED_DIR,
  VIEWPORT_DESKTOP, VIEWPORT_MOBILE, DEVICE_SCALE_FACTOR,
} from './config.mjs';
import { frameStill } from './frame.mjs';

if (!fs.existsSync(STATE_FILE)) {
  console.error(`✗ No saved session at ${STATE_FILE}. Run: node scripts/capture/auth.mjs first.`);
  process.exit(1);
}

const WEDDING_SLUG = 'john-suzanne'; // John & Suzanne — discovered read-only via WeddingDetails.slug

// Guest RSVP token — generated once, deliberately, via the real UI action
// ("Copy links" for guest "Jay Smith"), explicitly authorized. Not
// regenerated by this script; if the token file is missing, that shot is
// skipped rather than silently creating a new one.
const RSVP_TOKEN_FILE = path.join(path.dirname(STATE_FILE), 'rsvp-token.txt');
const RSVP_TOKEN = fs.existsSync(RSVP_TOKEN_FILE) ? fs.readFileSync(RSVP_TOKEN_FILE, 'utf8').trim() : null;

const SHOTS = [
  {
    name: '01-design-studio-universe-wall',
    url: `${BASE_URL}/studio/universe`,
    viewport: VIEWPORT_DESKTOP,
    settle: async (page) => { await page.waitForSelector('text=/universe/i', { timeout: 15000 }).catch(() => {}); await page.waitForTimeout(1500); },
  },
  {
    name: '02-entrance-moment-landing',
    url: `${BASE_URL}/w/${WEDDING_SLUG}`,
    viewport: VIEWPORT_DESKTOP,
    settle: async (page) => { await page.waitForTimeout(3500); }, // entrance animation needs time to resolve
  },
  {
    // Swapped from /our-story: John & Suzanne's ourStoryContent is
    // placeholder test text ("ghfghfnbv") with an empty photo gallery —
    // real for this account, but not a presentable "world page". Checked
    // every content field on the record (read-only) and guestSuiteAccommodation
    // is the one genuinely filled-in page: a real venue (Crown Sydney)
    // with a real rating.
    name: '03-world-page-stay',
    url: `${BASE_URL}/w/${WEDDING_SLUG}/stay`,
    viewport: VIEWPORT_DESKTOP,
    settle: async (page) => {
      await page.waitForTimeout(2500);
      await page.mouse.wheel(0, 500);
      await page.waitForLoadState('networkidle').catch(() => {}); // venue photos load from Google Places, can be slow
      await page.waitForTimeout(2000);
    },
  },
  {
    // Swapped from /Invitations: that account has never created an
    // Invitation record, so it only shows the blank "Create your wedding
    // website" first-run wizard — not a real money shot, and clicking
    // through would create data. /website-editor (StudioWebsite.jsx) is
    // the drag-and-drop site builder, already fully populated for this
    // wedding (active Kyoto universe, real pages) — a truer "builder in
    // use" shot than an empty wizard would have been.
    name: '04-website-builder',
    url: `${BASE_URL}/website-editor`,
    viewport: VIEWPORT_DESKTOP,
    settle: async (page) => { await page.waitForLoadState('networkidle'); await page.waitForTimeout(1500); },
  },
  {
    name: '05-guest-list',
    url: `${BASE_URL}/Guests`,
    viewport: VIEWPORT_DESKTOP,
    settle: async (page) => {
      await page.waitForLoadState('networkidle');
      await page.waitForTimeout(800);
      // Shot hygiene: make sure no row checkbox is left checked from any
      // prior run and no avatar/profile menu is open.
      await page.keyboard.press('Escape').catch(() => {});
    },
  },
  {
    name: '06-seating-canvas',
    url: `${BASE_URL}/Seating`,
    viewport: VIEWPORT_DESKTOP,
    settle: async (page) => { await page.waitForLoadState('networkidle'); await page.waitForTimeout(1200); },
  },
];

if (RSVP_TOKEN) {
  SHOTS.push({
    name: '07-rsvp-mobile',
    url: `${BASE_URL}/rsvp/${RSVP_TOKEN}`,
    viewport: VIEWPORT_MOBILE,
    settle: async (page) => { await page.waitForLoadState('networkidle'); await page.waitForTimeout(1000); },
  });
} else {
  console.warn('⚠ No RSVP token found at', RSVP_TOKEN_FILE, '— skipping the mobile RSVP shot.');
}

const browser = await chromium.launch();
const results = [];

for (const shot of SHOTS) {
  const context = await browser.newContext({
    storageState: shot.url.includes('/rsvp/') ? undefined : STATE_FILE, // RSVP guest link needs no login
    viewport: shot.viewport,
    deviceScaleFactor: DEVICE_SCALE_FACTOR,
    colorScheme: 'light',
  });
  const page = await context.newPage();
  console.log(`→ ${shot.name}: ${shot.url}`);
  try {
    await page.goto(shot.url, { waitUntil: 'domcontentloaded', timeout: 30000 });
    await shot.settle(page);

    const rawPath = path.join(RAW_DIR, `${shot.name}.png`);
    await page.screenshot({ path: rawPath, fullPage: false });

    const processedPath = path.join(PROCESSED_DIR, `${shot.name}.png`);
    const displayUrl = shot.url.replace(/^https?:\/\//, '');
    await frameStill({
      screenshotPath: rawPath,
      url: displayUrl,
      outputPath: processedPath,
      contentWidth: shot.viewport.width,
      contentHeight: shot.viewport.height,
      scale: DEVICE_SCALE_FACTOR,
    });

    console.log(`  ✓ saved ${processedPath}`);
    results.push({ name: shot.name, url: shot.url, path: processedPath, ok: true });
  } catch (err) {
    console.error(`  ✗ ${shot.name} failed: ${err.message}`);
    results.push({ name: shot.name, url: shot.url, ok: false, error: err.message });
  } finally {
    await context.close();
  }
}

await browser.close();

console.log('\n' + '='.repeat(60));
console.log('Stills summary:');
for (const r of results) console.log(`  ${r.ok ? '✓' : '✗'} ${r.name}`);
console.log('='.repeat(60));

fs.writeFileSync(
  path.join(RAW_DIR, '..', 'stills-report.json'),
  JSON.stringify(results, null, 2)
);

if (results.some(r => !r.ok)) process.exit(1);
